root: true
env:
  node: true
extends: 'eslint:recommended'
rules:
  array-bracket-spacing:  [ 2, 'never']
  block-spacing:           [ 2, 'always' ]
  brace-style:             [ 2, '1tbs', { 'allowSingleLine': false }]
  comma-style:             [ 2, 'last' ]
  curly:                   [ 2, 'all' ]
  dot-location:            [ 2, 'property' ]
  global-require:          0
  indent:                  [ 2, 2, { 'SwitchCase': 1 }]
  linebreak-style:         [ 0, 'windows' ]
  multiline-comment-style: [ 2, 'starred-block' ]
  no-multiple-empty-lines: [ 2, { 'max': 1, 'maxBOF': 0, 'maxEOF': 1 }]
  no-param-reassign:       1
  no-trailing-spaces:      [ 2, { 'skipBlankLines': false, 'ignoreComments': false }]
  no-undef:                [ 1, { 'typeof': true }]
  no-unused-vars:          [ 1, { 'vars': 'local', 'args': 'after-used', 'ignoreRestSiblings': false }]
  object-curly-spacing:    [ 2, 'always', { 'objectsInObjects': false }]
  quotes:                  [ 2, 'single']
  semi:                    [ 2, 'always' ]
  semi-spacing:            [ 2, { 'before': false, 'after': true }]
  space-before-blocks:     [ 2, 'always' ]
  space-before-function-paren: [ 2, { 'anonymous': 'always', 'named': 'never', 'asyncArrow': 'always' }]
  spaced-comment:          [ 2, "always", {
    "line": {
      "markers": ["/"],
      "exceptions": ["-", "+"]
    },
    "block": {
      "markers": ["!"],
      "exceptions": ["*"],
      "balanced": true
    }
  }]
  space-in-parens:         [ 2, 'never']
